# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170904_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(max_length=30, verbose_name='ToDo名'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='cms.ToDoList'),
        ),
    ]
