# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170904_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todolist_name',
            field=models.CharField(max_length=30, verbose_name='ToDoリスト名'),
        ),
    ]
