# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170904_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(max_length=100, verbose_name='ToDo名'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todolist_name',
            field=models.CharField(max_length=100, verbose_name='ToDoリスト名'),
        ),
    ]
