# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170909_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='todolist_name',
            field=models.CharField(max_length=60, verbose_name='ToDoリスト名'),
        ),
    ]
